{% set version = "1.5.2" %}

package:
  name: pkgconfig
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pkgconfig/pkgconfig-{{ version }}.tar.gz
  sha256: 38d612488f0633755a2e7a8acab6c01d20d63dbc31af75e2a9ac98a6f638ca94

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - nose >=1.0
  run:
    - python
    - pkg-config        # [unix]
    - m2w64-pkg-config  # [win]

test:
  imports:
    - pkgconfig

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python interface to the pkg-config command line tool'

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
