{% set name = "pkgconfig" %}
{% set version = "1.2.2" %}
{% set sha256 = "3f19a8eba1c6fc88a32c5e2a2ce2a25cefb58e530541979202b8c96d650bbddb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/matze/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - nose >=1.0
  run:
    - python
    - pkg-config        # [unix]
    - m2w64-pkg-config  # [win]

test:
  imports:
    - pkgconfig

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python interface to the pkg-config command line tool'
  
  description: |
    pkgconfig is a Python module to interface with the pkg-config command 
    line tool and supports Python 2.6+.
  doc_url: https://people.freedesktop.org/~dbn/pkg-config-guide.html
  dev_url: hhttps://github.com/matze/pkgconfig
  doc_source_url: 

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
