{% set version = "1.5.5" %}

package:
  name: pkgconfig
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pkgconfig/pkgconfig-{{ version }}.tar.gz
  sha256: deb4163ef11f75b520d822d9505c1f462761b4309b1bb713d08689759ea8b899

build:
  number: 0
  skip: true  # [py<33]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
    - setuptools
    - wheel
  run:
    - python
    - pkg-config        # [unix]
    - m2w64-pkg-config  # [win]

test:
  imports:
    - pkgconfig
    - pkgconfig.pkgconfig
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python interface to the pkg-config command line tool'
  dev_url: https://github.com/matze/pkgconfig
  doc_url: https://github.com/matze/pkgconfig/blob/master/README.rst


extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
