{% set name = "pkgconfig" %}
{% set version = "1.3.1" %}
{% set sha256 = "b4b8277cf33df2bfdd73da2bc4faab1b4b65b6d12e295aa6c70987642bcfb5c7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/matze/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - nose >=1.0
  run:
    - python
    - pkg-config        # [unix]
    - m2w64-pkg-config  # [win]

test:
  imports:
    - pkgconfig

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python interface to the pkg-config command line tool'

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
