{% set version = "1.5.1" %}

package:
  name: pkgconfig
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pkgconfig/pkgconfig-{{ version }}.tar.gz
  sha256: 97bfe3d981bab675d5ea3ef259045d7919c93897db7d3b59d4e8593cba8d354f

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - nose >=1.0
  run:
    - python
    - poetry
    - pkg-config        # [unix]
    - m2w64-pkg-config  # [win]

test:
  imports:
    - pkgconfig

about:
  home: https://github.com/matze/pkgconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python interface to the pkg-config command line tool'

extra:
  recipe-maintainers:
    - jakirkham
    - lbdreyer
    - ocefpaf
