travis:
  secure:
    BINSTAR_TOKEN: nh5l+SguFcoHyKbbAe3zKqS6PjjUuUZJdDlxzcOsNIcmtW1kajkWirLq+kinu24UdCjeOphtIhkNc1odrItYWF8obgNsR0anNWJ63EP5sTOLS6w/31f+xBz59em2J2twHaIZmcL7bGy4PCwKsHozJF4dA/cn/P7SjYLbBXR4JDIdKdEYAFB7CbolFEEVTn6qX494X5JmTxoIr1e+mRM9zWyD/4DvT+r9oVGe7ZB5LDfSd3aoRqT5DPVcyg6y6ZREBuIch5XB5fsFLgIKFLKWEncD6nCJNsPA1igRGCTHuGo13ec+hMnAoRFEIwwsXFtAFSSvWjCte1wnCvLykx3j5B7/QI+v35secrmuNlQAcgCel7Gb+j4zxOCjo3FBsDY02Qf4LchKxWjmAHFEAu13KD9fo03e7gpEeT9Mz4o9hcLDs7xGwJX0kEbrSpkizezFBkej0Ts4TFfx4W2GQpvQOtEda5PLLNWaFluKNfih+mdRF827KIZUNqOk4APfXF/6eH4J93nKx2mCphoEE2OzCriWsVm65vrDtPrFaj0FkoONsm8w6Kv4a/n3gPJuUnAZsLsOSJSssehVISRs+N1RNXjkyvmlemyhR6RJQNlZ4MLGlPgERnRiMD+2ttq4k6m4DMsK1j81y83XAkhe/DWG/GiCQ+1zXp7TGWb8Md/yXuw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
